ci: fix n8n socket race condition

diff --git a/infra/jenkins/Jenkinsfile b/infra/jenkins/Jenkinsfile
--- a/infra/jenkins/Jenkinsfile
+++ b/infra/jenkins/Jenkinsfile
@@ -212,9 +212,23 @@ pipeline {
 
                     echo "Démarrage de la stack..."
                     sh "docker rm -f n8n || true"
-                    echo "Waiting for n8n to properly kill its processes..."
-                    sh "sleep 2"
+                    echo "⏳ Attente de la libération du port 5679 par WSL2..."
+                    retry(10) { // On essaie 10 fois
+                        sh """
+                            # Si on ne trouve pas de processus sur le port, on sort avec succès
+                            # Sinon on attend 2s et on échoue (ce qui déclenche le retry)
+                            if ! (netstat -an | grep 5679 | grep LISTEN); then
+                                exit 0
+                            else
+                                sleep 2
+                                exit 1
+                            fi
+                        """
+                    }
                     sh "docker compose up -d --remove-orphans --force-recreate \$(docker compose config --services | grep -vE 'jenkins-srm|sonarqube|sonar-db')"
+
+                    echo "Cleaning up...."
+                    sh "docker system prune -f"
                 }
             }
         }
